// Generated by tools/build-sprites.py -- do not edit by hand.
window.SPRITE_MANIFEST = {
 "standingHeight": 132,
 "characters": [
  {
   "key": "monkey",
   "label": "Monkey",
   "mirror": false,
   "sequences": {
    "aim": [
     {
      "src": "sprites/monkey/aim/01.png",
      "w": 79.52,
      "h": 116.18,
      "footX": 43.53,
      "footY": 116.18
     },
     {
      "src": "sprites/monkey/aim/02.png",
      "w": 82.4,
      "h": 112.2,
      "footX": 45.87,
      "footY": 112.2
     }
    ],
    "break_banana": [
     {
      "src": "sprites/monkey/break_banana/01.png",
      "w": 102.62,
      "h": 121.88,
      "footX": 53.31,
      "footY": 121.88
     },
     {
      "src": "sprites/monkey/break_banana/02.png",
      "w": 96.9,
      "h": 121.88,
      "footX": 48.35,
      "footY": 121.88
     },
     {
      "src": "sprites/monkey/break_banana/03.png",
      "w": 95.56,
      "h": 121.69,
      "footX": 47.68,
      "footY": 121.69
     },
     {
      "src": "sprites/monkey/break_banana/04.png",
      "w": 108.72,
      "h": 120.93,
      "footX": 50.64,
      "footY": 120.93
     }
    ],
    "break_wave": [
     {
      "src": "sprites/monkey/break_wave/01.png",
      "w": 93.68,
      "h": 127.02,
      "footX": 47.93,
      "footY": 127.02
     },
     {
      "src": "sprites/monkey/break_wave/02.png",
      "w": 96.22,
      "h": 110.9,
      "footX": 45.48,
      "footY": 110.9
     },
     {
      "src": "sprites/monkey/break_wave/03.png",
      "w": 99.48,
      "h": 112.71,
      "footX": 45.93,
      "footY": 112.71
     },
     {
      "src": "sprites/monkey/break_wave/04.png",
      "w": 93.86,
      "h": 108.72,
      "footX": 47.75,
      "footY": 108.72
     }
    ],
    "celebrate": [
     {
      "src": "sprites/monkey/celebrate/01.png",
      "w": 94.0,
      "h": 153.92,
      "footX": 41.38,
      "footY": 153.92
     },
     {
      "src": "sprites/monkey/celebrate/02.png",
      "w": 96.51,
      "h": 121.69,
      "footX": 47.08,
      "footY": 121.69
     }
    ],
    "celebrate_flip": [
     {
      "src": "sprites/monkey/celebrate_flip/01.png",
      "w": 73.01,
      "h": 86.29,
      "footX": 36.51,
      "footY": 86.29
     },
     {
      "src": "sprites/monkey/celebrate_flip/02.png",
      "w": 73.46,
      "h": 108.42,
      "footX": 36.51,
      "footY": 117.71
     },
     {
      "src": "sprites/monkey/celebrate_flip/03.png",
      "w": 71.91,
      "h": 131.43,
      "footX": 36.51,
      "footY": 132.31
     },
     {
      "src": "sprites/monkey/celebrate_flip/04.png",
      "w": 79.87,
      "h": 82.97,
      "footX": 36.51,
      "footY": 93.81
     },
     {
      "src": "sprites/monkey/celebrate_flip/05.png",
      "w": 96.47,
      "h": 70.36,
      "footX": 36.51,
      "footY": 70.36
     },
     {
      "src": "sprites/monkey/celebrate_flip/06.png",
      "w": 69.7,
      "h": 127.22,
      "footX": 36.51,
      "footY": 127.22
     }
    ],
    "celebrate_pump": [
     {
      "src": "sprites/monkey/celebrate_pump/01.png",
      "w": 95.37,
      "h": 132.56,
      "footX": 45.87,
      "footY": 132.56
     },
     {
      "src": "sprites/monkey/celebrate_pump/02.png",
      "w": 97.28,
      "h": 117.11,
      "footX": 48.54,
      "footY": 117.3
     },
     {
      "src": "sprites/monkey/celebrate_pump/03.png",
      "w": 97.28,
      "h": 117.69,
      "footX": 48.54,
      "footY": 117.88
     }
    ],
    "charge": [
     {
      "src": "sprites/monkey/charge/01.png",
      "w": 90.55,
      "h": 115.65,
      "footX": 52.08,
      "footY": 115.65
     },
     {
      "src": "sprites/monkey/charge/02.png",
      "w": 83.66,
      "h": 102.19,
      "footX": 44.78,
      "footY": 102.19
     },
     {
      "src": "sprites/monkey/charge/03.png",
      "w": 83.99,
      "h": 86.77,
      "footX": 44.7,
      "footY": 86.77
     }
    ],
    "dribble_idle": [
     {
      "src": "sprites/monkey/dribble_idle/01.png",
      "w": 98.04,
      "h": 116.16,
      "footX": 49.31,
      "footY": 116.16
     },
     {
      "src": "sprites/monkey/dribble_idle/02.png",
      "w": 95.56,
      "h": 117.11,
      "footX": 47.02,
      "footY": 117.11
     },
     {
      "src": "sprites/monkey/dribble_idle/03.png",
      "w": 95.56,
      "h": 118.45,
      "footX": 47.3,
      "footY": 118.45
     },
     {
      "src": "sprites/monkey/dribble_idle/04.png",
      "w": 96.7,
      "h": 116.54,
      "footX": 49.21,
      "footY": 116.54
     }
    ],
    "gameover": [
     {
      "src": "sprites/monkey/gameover/01.png",
      "w": 113.47,
      "h": 98.86,
      "footX": 48.26,
      "footY": 98.86
     },
     {
      "src": "sprites/monkey/gameover/02.png",
      "w": 116.82,
      "h": 115.15,
      "footX": 48.76,
      "footY": 115.15
     }
    ],
    "panic": [
     {
      "src": "sprites/monkey/panic/01.png",
      "w": 94.77,
      "h": 113.25,
      "footX": 47.29,
      "footY": 113.43
     },
     {
      "src": "sprites/monkey/panic/02.png",
      "w": 94.23,
      "h": 126.12,
      "footX": 47.02,
      "footY": 126.12
     },
     {
      "src": "sprites/monkey/panic/03.png",
      "w": 94.77,
      "h": 115.61,
      "footX": 47.29,
      "footY": 115.61
     },
     {
      "src": "sprites/monkey/panic/04.png",
      "w": 93.68,
      "h": 126.12,
      "footX": 46.75,
      "footY": 126.12
     }
    ],
    "pickup": [
     {
      "src": "sprites/monkey/pickup/01.png",
      "w": 97.28,
      "h": 101.82,
      "footX": 48.56,
      "footY": 102.3
     },
     {
      "src": "sprites/monkey/pickup/02.png",
      "w": 97.44,
      "h": 112.68,
      "footX": 48.64,
      "footY": 112.68
     },
     {
      "src": "sprites/monkey/pickup/03.png",
      "w": 98.09,
      "h": 115.27,
      "footX": 50.91,
      "footY": 115.76
     }
    ],
    "run_dribble_l": [
     {
      "src": "sprites/monkey/run_dribble_l/01.png",
      "w": 103.56,
      "h": 117.58,
      "footX": 57.67,
      "footY": 117.58
     },
     {
      "src": "sprites/monkey/run_dribble_l/02.png",
      "w": 95.89,
      "h": 116.83,
      "footX": 47.85,
      "footY": 117.39
     },
     {
      "src": "sprites/monkey/run_dribble_l/03.png",
      "w": 99.44,
      "h": 117.58,
      "footX": 55.24,
      "footY": 117.58
     },
     {
      "src": "sprites/monkey/run_dribble_l/04.png",
      "w": 91.41,
      "h": 117.58,
      "footX": 45.61,
      "footY": 117.58
     }
    ],
    "run_dribble_r": [
     {
      "src": "sprites/monkey/run_dribble_r/01.png",
      "w": 102.2,
      "h": 120.86,
      "footX": 47.02,
      "footY": 121.41
     },
     {
      "src": "sprites/monkey/run_dribble_r/02.png",
      "w": 90.6,
      "h": 120.86,
      "footX": 45.21,
      "footY": 121.41
     },
     {
      "src": "sprites/monkey/run_dribble_r/03.png",
      "w": 89.15,
      "h": 120.86,
      "footX": 42.13,
      "footY": 121.41
     },
     {
      "src": "sprites/monkey/run_dribble_r/04.png",
      "w": 91.87,
      "h": 120.68,
      "footX": 45.84,
      "footY": 120.68
     }
    ],
    "run_l": [
     {
      "src": "sprites/monkey/run_l/01.png",
      "w": 118.35,
      "h": 111.95,
      "footX": 59.11,
      "footY": 111.95
     },
     {
      "src": "sprites/monkey/run_l/02.png",
      "w": 115.15,
      "h": 111.95,
      "footX": 57.51,
      "footY": 111.95
     }
    ],
    "run_r": [
     {
      "src": "sprites/monkey/run_r/01.png",
      "w": 116.49,
      "h": 111.43,
      "footX": 55.87,
      "footY": 111.43
     },
     {
      "src": "sprites/monkey/run_r/02.png",
      "w": 109.65,
      "h": 111.43,
      "footX": 54.75,
      "footY": 111.43
     }
    ],
    "shot": [
     {
      "src": "sprites/monkey/shot/01.png",
      "w": 80.68,
      "h": 87.68,
      "footX": 41.51,
      "footY": 87.68
     },
     {
      "src": "sprites/monkey/shot/02.png",
      "w": 87.14,
      "h": 121.02,
      "footX": 53.25,
      "footY": 121.2
     },
     {
      "src": "sprites/monkey/shot/03.png",
      "w": 78.35,
      "h": 144.51,
      "footX": 48.86,
      "footY": 145.77
     },
     {
      "src": "sprites/monkey/shot/04.png",
      "w": 68.13,
      "h": 137.16,
      "footX": 39.27,
      "footY": 137.34
     }
    ],
    "steal_l": [
     {
      "src": "sprites/monkey/steal_l/01.png",
      "w": 104.07,
      "h": 109.67,
      "footX": 56.45,
      "footY": 109.67
     },
     {
      "src": "sprites/monkey/steal_l/02.png",
      "w": 166.12,
      "h": 104.5,
      "footX": 85.64,
      "footY": 105.79
     },
     {
      "src": "sprites/monkey/steal_l/03.png",
      "w": 95.45,
      "h": 116.56,
      "footX": 47.62,
      "footY": 116.56
     }
    ],
    "steal_r": [
     {
      "src": "sprites/monkey/steal_r/01.png",
      "w": 97.09,
      "h": 113.72,
      "footX": 48.13,
      "footY": 113.72
     },
     {
      "src": "sprites/monkey/steal_r/02.png",
      "w": 155.51,
      "h": 105.82,
      "footX": 66.43,
      "footY": 106.24
     },
     {
      "src": "sprites/monkey/steal_r/03.png",
      "w": 93.14,
      "h": 116.63,
      "footX": 46.47,
      "footY": 117.05
     }
    ],
    "stolen": [
     {
      "src": "sprites/monkey/stolen/01.png",
      "w": 98.84,
      "h": 128.76,
      "footX": 51.35,
      "footY": 129.15
     },
     {
      "src": "sprites/monkey/stolen/02.png",
      "w": 88.42,
      "h": 133.78,
      "footX": 44.11,
      "footY": 133.78
     },
     {
      "src": "sprites/monkey/stolen/03.png",
      "w": 94.4,
      "h": 116.8,
      "footX": 47.1,
      "footY": 117.18
     }
    ],
    "turn": [
     {
      "src": "sprites/monkey/turn/01.png",
      "w": 95.42,
      "h": 116.16,
      "footX": 52.44,
      "footY": 116.16
     },
     {
      "src": "sprites/monkey/turn/02.png",
      "w": 88.45,
      "h": 115.33,
      "footX": 46.13,
      "footY": 115.33
     }
    ]
   },
   "ballSide": {
    "dribble_idle": -1,
    "break_banana": -1,
    "break_wave": -1,
    "pickup": -1,
    "panic": -1,
    "run_dribble_r": 1,
    "run_dribble_l": -1
   },
   "storySeq": {
    "break_banana": null
   },
   "pickupBall": [
    [
     0,
     0
    ],
    [
     0,
     0
    ],
    [
     1,
     0.42
    ]
   ],
   "handX": 13.52,
   "handY": -145.77
  },
  {
   "key": "nba",
   "label": "NBA Player",
   "mirror": false,
   "sequences": {
    "aim": [
     {
      "src": "sprites/nba/aim/01.png",
      "w": 98.69,
      "h": 138.38,
      "footX": 49.24,
      "footY": 138.38
     },
     {
      "src": "sprites/nba/aim/02.png",
      "w": 100.96,
      "h": 135.29,
      "footX": 50.37,
      "footY": 135.29
     }
    ],
    "break_flex": [
     {
      "src": "sprites/nba/break_flex/01.png",
      "w": 105.33,
      "h": 144.57,
      "footX": 53.95,
      "footY": 144.57
     },
     {
      "src": "sprites/nba/break_flex/02.png",
      "w": 104.17,
      "h": 134.99,
      "footX": 51.97,
      "footY": 134.99
     },
     {
      "src": "sprites/nba/break_flex/03.png",
      "w": 105.8,
      "h": 137.8,
      "footX": 55.35,
      "footY": 137.8
     },
     {
      "src": "sprites/nba/break_flex/04.png",
      "w": 93.89,
      "h": 139.2,
      "footX": 46.83,
      "footY": 139.2
     }
    ],
    "break_yawn": [
     {
      "src": "sprites/nba/break_yawn/01.png",
      "w": 103.35,
      "h": 138.93,
      "footX": 52.91,
      "footY": 138.93
     },
     {
      "src": "sprites/nba/break_yawn/02.png",
      "w": 99.52,
      "h": 141.85,
      "footX": 49.99,
      "footY": 141.85
     },
     {
      "src": "sprites/nba/break_yawn/03.png",
      "w": 99.3,
      "h": 138.25,
      "footX": 49.54,
      "footY": 138.25
     },
     {
      "src": "sprites/nba/break_yawn/04.png",
      "w": 93.44,
      "h": 137.58,
      "footX": 47.28,
      "footY": 137.58
     }
    ],
    "celebrate": [
     {
      "src": "sprites/nba/celebrate/01.png",
      "w": 117.28,
      "h": 171.91,
      "footX": 58.4,
      "footY": 171.91
     },
     {
      "src": "sprites/nba/celebrate/02.png",
      "w": 120.92,
      "h": 131.6,
      "footX": 60.34,
      "footY": 131.6
     }
    ],
    "celebrate_crowd": [
     {
      "src": "sprites/nba/celebrate_crowd/01.png",
      "w": 138.95,
      "h": 147.45,
      "footX": 70.98,
      "footY": 147.45
     },
     {
      "src": "sprites/nba/celebrate_crowd/02.png",
      "w": 95.37,
      "h": 179.51,
      "footX": 46.32,
      "footY": 179.51
     },
     {
      "src": "sprites/nba/celebrate_crowd/03.png",
      "w": 95.37,
      "h": 142.51,
      "footX": 47.96,
      "footY": 142.51
     },
     {
      "src": "sprites/nba/celebrate_crowd/04.png",
      "w": 93.46,
      "h": 178.96,
      "footX": 46.32,
      "footY": 178.96
     },
     {
      "src": "sprites/nba/celebrate_crowd/05.png",
      "w": 102.23,
      "h": 132.92,
      "footX": 53.17,
      "footY": 132.92
     }
    ],
    "celebrate_pump": [
     {
      "src": "sprites/nba/celebrate_pump/01.png",
      "w": 92.61,
      "h": 154.57,
      "footX": 46.2,
      "footY": 155.01
     },
     {
      "src": "sprites/nba/celebrate_pump/02.png",
      "w": 115.6,
      "h": 131.14,
      "footX": 57.69,
      "footY": 131.14
     },
     {
      "src": "sprites/nba/celebrate_pump/03.png",
      "w": 115.6,
      "h": 135.52,
      "footX": 57.69,
      "footY": 135.52
     }
    ],
    "charge": [
     {
      "src": "sprites/nba/charge/01.png",
      "w": 103.03,
      "h": 132.11,
      "footX": 51.41,
      "footY": 132.11
     },
     {
      "src": "sprites/nba/charge/02.png",
      "w": 106.98,
      "h": 113.0,
      "footX": 53.39,
      "footY": 113.42
     },
     {
      "src": "sprites/nba/charge/03.png",
      "w": 101.58,
      "h": 93.68,
      "footX": 50.68,
      "footY": 93.68
     }
    ],
    "dribble_idle": [
     {
      "src": "sprites/nba/dribble_idle/01.png",
      "w": 95.64,
      "h": 136.4,
      "footX": 49.0,
      "footY": 136.4
     },
     {
      "src": "sprites/nba/dribble_idle/02.png",
      "w": 91.87,
      "h": 136.4,
      "footX": 45.82,
      "footY": 136.4
     },
     {
      "src": "sprites/nba/dribble_idle/03.png",
      "w": 91.87,
      "h": 136.4,
      "footX": 45.82,
      "footY": 136.4
     },
     {
      "src": "sprites/nba/dribble_idle/04.png",
      "w": 91.64,
      "h": 136.4,
      "footX": 45.7,
      "footY": 136.4
     }
    ],
    "gameover": [
     {
      "src": "sprites/nba/gameover/01.png",
      "w": 114.11,
      "h": 122.83,
      "footX": 56.96,
      "footY": 122.83
     },
     {
      "src": "sprites/nba/gameover/02.png",
      "w": 113.51,
      "h": 137.22,
      "footX": 56.65,
      "footY": 137.22
     }
    ],
    "panic": [
     {
      "src": "sprites/nba/panic/01.png",
      "w": 84.3,
      "h": 138.85,
      "footX": 42.02,
      "footY": 138.85
     },
     {
      "src": "sprites/nba/panic/02.png",
      "w": 85.87,
      "h": 138.85,
      "footX": 43.72,
      "footY": 138.85
     },
     {
      "src": "sprites/nba/panic/03.png",
      "w": 85.35,
      "h": 138.85,
      "footX": 46.33,
      "footY": 138.85
     },
     {
      "src": "sprites/nba/panic/04.png",
      "w": 83.52,
      "h": 138.85,
      "footX": 42.94,
      "footY": 138.85
     },
     {
      "src": "sprites/nba/panic/05.png",
      "w": 85.61,
      "h": 138.85,
      "footX": 46.07,
      "footY": 138.85
     },
     {
      "src": "sprites/nba/panic/06.png",
      "w": 80.91,
      "h": 138.85,
      "footX": 42.02,
      "footY": 138.85
     }
    ],
    "pickup": [
     {
      "src": "sprites/nba/pickup/01.png",
      "w": 90.26,
      "h": 115.24,
      "footX": 45.04,
      "footY": 115.24
     },
     {
      "src": "sprites/nba/pickup/02.png",
      "w": 85.27,
      "h": 99.7,
      "footX": 42.54,
      "footY": 99.7
     },
     {
      "src": "sprites/nba/pickup/03.png",
      "w": 86.57,
      "h": 123.56,
      "footX": 43.19,
      "footY": 123.56
     }
    ],
    "run_dribble_l": [
     {
      "src": "sprites/nba/run_dribble_l/01.png",
      "w": 119.44,
      "h": 136.54,
      "footX": 45.7,
      "footY": 137.68
     },
     {
      "src": "sprites/nba/run_dribble_l/02.png",
      "w": 84.34,
      "h": 137.22,
      "footX": 37.84,
      "footY": 138.13
     },
     {
      "src": "sprites/nba/run_dribble_l/03.png",
      "w": 105.77,
      "h": 137.45,
      "footX": 50.72,
      "footY": 138.13
     },
     {
      "src": "sprites/nba/run_dribble_l/04.png",
      "w": 84.34,
      "h": 138.13,
      "footX": 42.06,
      "footY": 138.13
     }
    ],
    "run_dribble_r": [
     {
      "src": "sprites/nba/run_dribble_r/01.png",
      "w": 100.69,
      "h": 136.3,
      "footX": 56.38,
      "footY": 136.3
     },
     {
      "src": "sprites/nba/run_dribble_r/02.png",
      "w": 84.58,
      "h": 132.91,
      "footX": 42.18,
      "footY": 136.3
     },
     {
      "src": "sprites/nba/run_dribble_r/03.png",
      "w": 98.35,
      "h": 136.3,
      "footX": 49.07,
      "footY": 136.3
     },
     {
      "src": "sprites/nba/run_dribble_r/04.png",
      "w": 75.67,
      "h": 132.91,
      "footX": 37.73,
      "footY": 136.3
     }
    ],
    "run_l": [
     {
      "src": "sprites/nba/run_l/01.png",
      "w": 117.67,
      "h": 138.09,
      "footX": 51.27,
      "footY": 140.15
     },
     {
      "src": "sprites/nba/run_l/02.png",
      "w": 73.63,
      "h": 140.15,
      "footX": 35.9,
      "footY": 140.15
     },
     {
      "src": "sprites/nba/run_l/03.png",
      "w": 118.82,
      "h": 138.55,
      "footX": 46.91,
      "footY": 138.55
     },
     {
      "src": "sprites/nba/run_l/04.png",
      "w": 77.3,
      "h": 138.78,
      "footX": 34.18,
      "footY": 138.78
     }
    ],
    "run_r": [
     {
      "src": "sprites/nba/run_r/01.png",
      "w": 121.75,
      "h": 135.73,
      "footX": 67.98,
      "footY": 136.41
     },
     {
      "src": "sprites/nba/run_r/02.png",
      "w": 78.24,
      "h": 136.41,
      "footX": 39.01,
      "footY": 136.41
     },
     {
      "src": "sprites/nba/run_r/03.png",
      "w": 127.39,
      "h": 136.41,
      "footX": 78.57,
      "footY": 136.41
     },
     {
      "src": "sprites/nba/run_r/04.png",
      "w": 72.15,
      "h": 135.28,
      "footX": 39.79,
      "footY": 135.28
     }
    ],
    "shot": [
     {
      "src": "sprites/nba/shot/01.png",
      "w": 89.16,
      "h": 100.57,
      "footX": 44.46,
      "footY": 100.57
     },
     {
      "src": "sprites/nba/shot/02.png",
      "w": 80.08,
      "h": 135.72,
      "footX": 39.93,
      "footY": 135.72
     },
     {
      "src": "sprites/nba/shot/03.png",
      "w": 63.09,
      "h": 179.26,
      "footX": 31.43,
      "footY": 179.26
     },
     {
      "src": "sprites/nba/shot/04.png",
      "w": 71.0,
      "h": 166.92,
      "footX": 35.39,
      "footY": 166.92
     }
    ],
    "steal_l": [
     {
      "src": "sprites/nba/steal_l/01.png",
      "w": 125.49,
      "h": 133.21,
      "footX": 74.57,
      "footY": 133.21
     },
     {
      "src": "sprites/nba/steal_l/02.png",
      "w": 174.19,
      "h": 120.81,
      "footX": 95.05,
      "footY": 120.81
     },
     {
      "src": "sprites/nba/steal_l/03.png",
      "w": 107.23,
      "h": 137.43,
      "footX": 54.43,
      "footY": 138.13
     }
    ],
    "steal_r": [
     {
      "src": "sprites/nba/steal_r/01.png",
      "w": 127.49,
      "h": 129.18,
      "footX": 49.08,
      "footY": 129.91
     },
     {
      "src": "sprites/nba/steal_r/02.png",
      "w": 185.17,
      "h": 128.21,
      "footX": 84.34,
      "footY": 128.94
     },
     {
      "src": "sprites/nba/steal_r/03.png",
      "w": 100.82,
      "h": 137.42,
      "footX": 50.29,
      "footY": 137.42
     }
    ],
    "stolen": [
     {
      "src": "sprites/nba/stolen/01.png",
      "w": 95.42,
      "h": 123.52,
      "footX": 48.42,
      "footY": 123.52
     },
     {
      "src": "sprites/nba/stolen/02.png",
      "w": 92.99,
      "h": 121.7,
      "footX": 47.1,
      "footY": 121.9
     },
     {
      "src": "sprites/nba/stolen/03.png",
      "w": 81.87,
      "h": 151.01,
      "footX": 40.83,
      "footY": 151.21
     }
    ],
    "turn": [
     {
      "src": "sprites/nba/turn/01.png",
      "w": 96.71,
      "h": 137.91,
      "footX": 48.27,
      "footY": 137.91
     },
     {
      "src": "sprites/nba/turn/02.png",
      "w": 91.54,
      "h": 136.88,
      "footX": 45.68,
      "footY": 136.88
     }
    ]
   },
   "ballSide": {
    "dribble_idle": -1,
    "run_dribble_l": -1,
    "break_flex": -1,
    "break_yawn": -1,
    "panic": -1
   },
   "apexFrame": {
    "dribble_idle": 2,
    "run_dribble_r": 1,
    "run_dribble_l": 1
   },
   "loopBounces": {
    "run_dribble_r": 2,
    "run_dribble_l": 2
   },
   "storySeq": {
    "break_flex": null,
    "break_yawn": null,
    "panic": [
     4,
     5
    ]
   },
   "standH": 145.2,
   "pickupBall": [
    [
     0,
     0
    ],
    [
     0,
     0
    ],
    [
     0,
     0.42
    ]
   ],
   "handX": -0.89,
   "handY": -179.26
  },
  {
   "key": "highschooler",
   "label": "High Schooler",
   "mirror": false,
   "sequences": {
    "aim": [
     {
      "src": "sprites/highschooler/aim/01.png",
      "w": 84.02,
      "h": 126.71,
      "footX": 41.92,
      "footY": 126.71
     },
     {
      "src": "sprites/highschooler/aim/02.png",
      "w": 85.72,
      "h": 120.42,
      "footX": 42.77,
      "footY": 120.42
     }
    ],
    "break_hair": [
     {
      "src": "sprites/highschooler/break_hair/01.png",
      "w": 83.47,
      "h": 126.9,
      "footX": 44.13,
      "footY": 126.9
     },
     {
      "src": "sprites/highschooler/break_hair/02.png",
      "w": 84.47,
      "h": 132.48,
      "footX": 44.92,
      "footY": 132.48
     },
     {
      "src": "sprites/highschooler/break_hair/03.png",
      "w": 86.06,
      "h": 137.26,
      "footX": 46.32,
      "footY": 137.26
     },
     {
      "src": "sprites/highschooler/break_hair/04.png",
      "w": 74.51,
      "h": 125.9,
      "footX": 39.34,
      "footY": 125.9
     }
    ],
    "break_phone": [
     {
      "src": "sprites/highschooler/break_phone/01.png",
      "w": 87.06,
      "h": 128.97,
      "footX": 45.15,
      "footY": 128.97
     },
     {
      "src": "sprites/highschooler/break_phone/02.png",
      "w": 82.4,
      "h": 123.1,
      "footX": 41.1,
      "footY": 123.1
     },
     {
      "src": "sprites/highschooler/break_phone/03.png",
      "w": 88.68,
      "h": 128.97,
      "footX": 46.06,
      "footY": 128.97
     },
     {
      "src": "sprites/highschooler/break_phone/04.png",
      "w": 82.0,
      "h": 126.54,
      "footX": 42.62,
      "footY": 126.54
     }
    ],
    "celebrate": [
     {
      "src": "sprites/highschooler/celebrate/01.png",
      "w": 90.94,
      "h": 160.31,
      "footX": 45.37,
      "footY": 161.09
     },
     {
      "src": "sprites/highschooler/celebrate/02.png",
      "w": 95.02,
      "h": 120.67,
      "footX": 47.41,
      "footY": 120.67
     }
    ],
    "celebrate_dab": [
     {
      "src": "sprites/highschooler/celebrate_dab/01.png",
      "w": 105.15,
      "h": 137.15,
      "footX": 49.93,
      "footY": 137.15
     },
     {
      "src": "sprites/highschooler/celebrate_dab/02.png",
      "w": 99.37,
      "h": 139.8,
      "footX": 42.23,
      "footY": 139.8
     },
     {
      "src": "sprites/highschooler/celebrate_dab/03.png",
      "w": 86.62,
      "h": 123.67,
      "footX": 43.19,
      "footY": 123.67
     },
     {
      "src": "sprites/highschooler/celebrate_dab/04.png",
      "w": 97.21,
      "h": 144.37,
      "footX": 55.58,
      "footY": 144.37
     },
     {
      "src": "sprites/highschooler/celebrate_dab/05.png",
      "w": 76.27,
      "h": 132.34,
      "footX": 38.02,
      "footY": 132.34
     }
    ],
    "celebrate_pump": [
     {
      "src": "sprites/highschooler/celebrate_pump/01.png",
      "w": 76.17,
      "h": 142.69,
      "footX": 37.98,
      "footY": 142.69
     },
     {
      "src": "sprites/highschooler/celebrate_pump/02.png",
      "w": 98.34,
      "h": 122.16,
      "footX": 49.07,
      "footY": 122.16
     },
     {
      "src": "sprites/highschooler/celebrate_pump/03.png",
      "w": 98.55,
      "h": 120.72,
      "footX": 49.17,
      "footY": 120.72
     }
    ],
    "charge": [
     {
      "src": "sprites/highschooler/charge/01.png",
      "w": 89.75,
      "h": 124.3,
      "footX": 44.78,
      "footY": 124.49
     },
     {
      "src": "sprites/highschooler/charge/02.png",
      "w": 89.36,
      "h": 107.7,
      "footX": 44.58,
      "footY": 107.89
     },
     {
      "src": "sprites/highschooler/charge/03.png",
      "w": 87.24,
      "h": 86.66,
      "footX": 43.52,
      "footY": 86.66
     }
    ],
    "dribble_idle": [
     {
      "src": "sprites/highschooler/dribble_idle/01.png",
      "w": 81.34,
      "h": 125.03,
      "footX": 40.57,
      "footY": 125.24
     },
     {
      "src": "sprites/highschooler/dribble_idle/02.png",
      "w": 81.55,
      "h": 125.87,
      "footX": 40.67,
      "footY": 125.87
     },
     {
      "src": "sprites/highschooler/dribble_idle/03.png",
      "w": 81.14,
      "h": 127.74,
      "footX": 40.46,
      "footY": 127.74
     },
     {
      "src": "sprites/highschooler/dribble_idle/04.png",
      "w": 81.14,
      "h": 126.49,
      "footX": 40.46,
      "footY": 126.7
     }
    ],
    "gameover": [
     {
      "src": "sprites/highschooler/gameover/01.png",
      "w": 89.65,
      "h": 107.34,
      "footX": 44.74,
      "footY": 107.34
     },
     {
      "src": "sprites/highschooler/gameover/02.png",
      "w": 90.32,
      "h": 122.7,
      "footX": 45.07,
      "footY": 122.7
     }
    ],
    "panic": [
     {
      "src": "sprites/highschooler/panic/01.png",
      "w": 79.32,
      "h": 126.18,
      "footX": 40.58,
      "footY": 126.18
     },
     {
      "src": "sprites/highschooler/panic/02.png",
      "w": 77.49,
      "h": 123.57,
      "footX": 39.01,
      "footY": 123.57
     },
     {
      "src": "sprites/highschooler/panic/03.png",
      "w": 78.01,
      "h": 126.97,
      "footX": 39.14,
      "footY": 126.97
     },
     {
      "src": "sprites/highschooler/panic/04.png",
      "w": 81.94,
      "h": 134.3,
      "footX": 42.15,
      "footY": 134.3
     },
     {
      "src": "sprites/highschooler/panic/05.png",
      "w": 84.56,
      "h": 141.89,
      "footX": 41.23,
      "footY": 141.89
     },
     {
      "src": "sprites/highschooler/panic/06.png",
      "w": 85.34,
      "h": 141.37,
      "footX": 42.93,
      "footY": 141.37
     }
    ],
    "pickup": [
     {
      "src": "sprites/highschooler/pickup/01.png",
      "w": 94.46,
      "h": 108.63,
      "footX": 47.12,
      "footY": 108.63
     },
     {
      "src": "sprites/highschooler/pickup/02.png",
      "w": 94.91,
      "h": 88.84,
      "footX": 47.34,
      "footY": 88.84
     },
     {
      "src": "sprites/highschooler/pickup/03.png",
      "w": 94.69,
      "h": 119.43,
      "footX": 47.23,
      "footY": 119.43
     }
    ],
    "run_dribble_l": [
     {
      "src": "sprites/highschooler/run_dribble_l/01.png",
      "w": 92.99,
      "h": 121.47,
      "footX": 34.65,
      "footY": 121.47
     },
     {
      "src": "sprites/highschooler/run_dribble_l/02.png",
      "w": 68.7,
      "h": 121.27,
      "footX": 30.67,
      "footY": 121.27
     },
     {
      "src": "sprites/highschooler/run_dribble_l/03.png",
      "w": 93.19,
      "h": 121.27,
      "footX": 39.43,
      "footY": 121.27
     },
     {
      "src": "sprites/highschooler/run_dribble_l/04.png",
      "w": 64.92,
      "h": 121.07,
      "footX": 31.46,
      "footY": 121.07
     }
    ],
    "run_dribble_r": [
     {
      "src": "sprites/highschooler/run_dribble_r/01.png",
      "w": 90.31,
      "h": 124.63,
      "footX": 55.29,
      "footY": 124.63
     },
     {
      "src": "sprites/highschooler/run_dribble_r/02.png",
      "w": 56.59,
      "h": 125.03,
      "footX": 28.5,
      "footY": 125.03
     },
     {
      "src": "sprites/highschooler/run_dribble_r/03.png",
      "w": 81.28,
      "h": 124.83,
      "footX": 37.13,
      "footY": 124.83
     },
     {
      "src": "sprites/highschooler/run_dribble_r/04.png",
      "w": 66.63,
      "h": 125.23,
      "footX": 33.21,
      "footY": 125.23
     }
    ],
    "run_l": [
     {
      "src": "sprites/highschooler/run_l/01.png",
      "w": 93.61,
      "h": 123.92,
      "footX": 39.07,
      "footY": 123.92
     },
     {
      "src": "sprites/highschooler/run_l/02.png",
      "w": 63.5,
      "h": 122.27,
      "footX": 30.21,
      "footY": 123.92
     },
     {
      "src": "sprites/highschooler/run_l/03.png",
      "w": 96.7,
      "h": 123.3,
      "footX": 37.83,
      "footY": 123.5
     },
     {
      "src": "sprites/highschooler/run_l/04.png",
      "w": 54.23,
      "h": 123.09,
      "footX": 27.32,
      "footY": 123.92
     }
    ],
    "run_r": [
     {
      "src": "sprites/highschooler/run_r/01.png",
      "w": 109.84,
      "h": 121.55,
      "footX": 58.58,
      "footY": 122.18
     },
     {
      "src": "sprites/highschooler/run_r/02.png",
      "w": 60.67,
      "h": 122.81,
      "footX": 30.23,
      "footY": 122.81
     },
     {
      "src": "sprites/highschooler/run_r/03.png",
      "w": 99.59,
      "h": 121.76,
      "footX": 61.3,
      "footY": 121.76
     },
     {
      "src": "sprites/highschooler/run_r/04.png",
      "w": 63.6,
      "h": 121.97,
      "footX": 36.61,
      "footY": 121.97
     }
    ],
    "shot": [
     {
      "src": "sprites/highschooler/shot/01.png",
      "w": 74.77,
      "h": 102.68,
      "footX": 37.28,
      "footY": 103.35
     },
     {
      "src": "sprites/highschooler/shot/02.png",
      "w": 76.56,
      "h": 137.5,
      "footX": 38.17,
      "footY": 138.17
     },
     {
      "src": "sprites/highschooler/shot/03.png",
      "w": 52.45,
      "h": 173.66,
      "footX": 26.12,
      "footY": 173.66
     },
     {
      "src": "sprites/highschooler/shot/04.png",
      "w": 62.27,
      "h": 158.03,
      "footX": 31.03,
      "footY": 158.25
     }
    ],
    "steal_l": [
     {
      "src": "sprites/highschooler/steal_l/01.png",
      "w": 105.54,
      "h": 122.35,
      "footX": 60.64,
      "footY": 122.35
     },
     {
      "src": "sprites/highschooler/steal_l/02.png",
      "w": 147.67,
      "h": 118.52,
      "footX": 83.62,
      "footY": 119.79
     },
     {
      "src": "sprites/highschooler/steal_l/03.png",
      "w": 87.66,
      "h": 123.62,
      "footX": 47.13,
      "footY": 124.05
     }
    ],
    "steal_r": [
     {
      "src": "sprites/highschooler/steal_r/01.png",
      "w": 97.58,
      "h": 120.28,
      "footX": 46.64,
      "footY": 120.28
     },
     {
      "src": "sprites/highschooler/steal_r/02.png",
      "w": 138.49,
      "h": 113.12,
      "footX": 61.37,
      "footY": 113.12
     },
     {
      "src": "sprites/highschooler/steal_r/03.png",
      "w": 91.23,
      "h": 120.49,
      "footX": 45.51,
      "footY": 120.49
     }
    ],
    "stolen": [
     {
      "src": "sprites/highschooler/stolen/01.png",
      "w": 96.61,
      "h": 118.91,
      "footX": 51.52,
      "footY": 118.91
     },
     {
      "src": "sprites/highschooler/stolen/02.png",
      "w": 94.34,
      "h": 119.1,
      "footX": 47.55,
      "footY": 119.1
     },
     {
      "src": "sprites/highschooler/stolen/03.png",
      "w": 80.16,
      "h": 140.47,
      "footX": 39.98,
      "footY": 140.47
     }
    ],
    "turn": [
     {
      "src": "sprites/highschooler/turn/01.png",
      "w": 86.94,
      "h": 127.13,
      "footX": 43.38,
      "footY": 128.04
     },
     {
      "src": "sprites/highschooler/turn/02.png",
      "w": 88.95,
      "h": 128.04,
      "footX": 44.38,
      "footY": 128.04
     }
    ]
   },
   "ballSide": {
    "dribble_idle": -1,
    "run_dribble_l": -1,
    "break_phone": -1,
    "break_hair": -1,
    "panic": -1
   },
   "apexFrame": {
    "dribble_idle": 2,
    "run_dribble_r": 1,
    "run_dribble_l": 1
   },
   "loopBounces": {
    "run_dribble_r": 2,
    "run_dribble_l": 2
   },
   "storySeq": {
    "break_phone": null,
    "break_hair": null,
    "panic": [
     4,
     5
    ]
   },
   "standH": 128.04,
   "pickupBall": [
    [
     0,
     0
    ],
    [
     0,
     0
    ],
    [
     0,
     0.42
    ]
   ],
   "handX": -0.14,
   "handY": -173.66
  },
  {
   "key": "zombie",
   "label": "Zombie",
   "mirror": false,
   "sequences": {
    "aim": [
     {
      "src": "sprites/zombie/aim/01.png",
      "w": 95.3,
      "h": 135.48,
      "footX": 47.55,
      "footY": 135.48
     },
     {
      "src": "sprites/zombie/aim/02.png",
      "w": 96.51,
      "h": 128.82,
      "footX": 48.15,
      "footY": 128.82
     }
    ],
    "break_face": [
     {
      "src": "sprites/zombie/break_face/01.png",
      "w": 86.52,
      "h": 131.85,
      "footX": 53.62,
      "footY": 131.85
     },
     {
      "src": "sprites/zombie/break_face/02.png",
      "w": 78.93,
      "h": 123.57,
      "footX": 46.14,
      "footY": 123.57
     },
     {
      "src": "sprites/zombie/break_face/03.png",
      "w": 111.37,
      "h": 139.45,
      "footX": 52.12,
      "footY": 139.45
     },
     {
      "src": "sprites/zombie/break_face/04.png",
      "w": 69.26,
      "h": 132.08,
      "footX": 38.31,
      "footY": 132.08
     }
    ],
    "break_head": [
     {
      "src": "sprites/zombie/break_head/01.png",
      "w": 76.97,
      "h": 138.63,
      "footX": 39.37,
      "footY": 138.63
     },
     {
      "src": "sprites/zombie/break_head/02.png",
      "w": 73.83,
      "h": 138.04,
      "footX": 37.6,
      "footY": 138.04
     },
     {
      "src": "sprites/zombie/break_head/03.png",
      "w": 75.21,
      "h": 133.53,
      "footX": 39.17,
      "footY": 133.53
     },
     {
      "src": "sprites/zombie/break_head/04.png",
      "w": 68.73,
      "h": 138.83,
      "footX": 34.27,
      "footY": 138.83
     }
    ],
    "celebrate": [
     {
      "src": "sprites/zombie/celebrate/01.png",
      "w": 89.13,
      "h": 151.45,
      "footX": 44.67,
      "footY": 151.45
     },
     {
      "src": "sprites/zombie/celebrate/02.png",
      "w": 102.53,
      "h": 119.33,
      "footX": 51.16,
      "footY": 119.33
     }
    ],
    "celebrate_collapse": [
     {
      "src": "sprites/zombie/celebrate_collapse/01.png",
      "w": 63.44,
      "h": 184.16,
      "footX": 33.65,
      "footY": 184.16
     },
     {
      "src": "sprites/zombie/celebrate_collapse/02.png",
      "w": 75.51,
      "h": 181.59,
      "footX": 31.08,
      "footY": 181.59
     },
     {
      "src": "sprites/zombie/celebrate_collapse/03.png",
      "w": 81.68,
      "h": 155.14,
      "footX": 48.8,
      "footY": 155.14
     },
     {
      "src": "sprites/zombie/celebrate_collapse/04.png",
      "w": 77.31,
      "h": 142.04,
      "footX": 39.94,
      "footY": 142.04
     },
     {
      "src": "sprites/zombie/celebrate_collapse/05.png",
      "w": 71.66,
      "h": 138.44,
      "footX": 35.7,
      "footY": 138.44
     }
    ],
    "celebrate_pump": [
     {
      "src": "sprites/zombie/celebrate_pump/01.png",
      "w": 81.28,
      "h": 150.52,
      "footX": 40.55,
      "footY": 150.52
     },
     {
      "src": "sprites/zombie/celebrate_pump/02.png",
      "w": 89.12,
      "h": 128.33,
      "footX": 44.47,
      "footY": 128.33
     },
     {
      "src": "sprites/zombie/celebrate_pump/03.png",
      "w": 87.02,
      "h": 127.95,
      "footX": 43.41,
      "footY": 127.95
     }
    ],
    "charge": [
     {
      "src": "sprites/zombie/charge/01.png",
      "w": 83.92,
      "h": 137.88,
      "footX": 41.87,
      "footY": 137.88
     },
     {
      "src": "sprites/zombie/charge/02.png",
      "w": 84.67,
      "h": 117.46,
      "footX": 42.24,
      "footY": 117.46
     },
     {
      "src": "sprites/zombie/charge/03.png",
      "w": 82.24,
      "h": 89.92,
      "footX": 41.03,
      "footY": 89.92
     }
    ],
    "dribble_idle": [
     {
      "src": "sprites/zombie/dribble_idle/01.png",
      "w": 86.7,
      "h": 128.67,
      "footX": 43.24,
      "footY": 128.88
     },
     {
      "src": "sprites/zombie/dribble_idle/02.png",
      "w": 86.91,
      "h": 128.88,
      "footX": 43.35,
      "footY": 128.88
     },
     {
      "src": "sprites/zombie/dribble_idle/03.png",
      "w": 86.49,
      "h": 128.88,
      "footX": 43.14,
      "footY": 129.09
     },
     {
      "src": "sprites/zombie/dribble_idle/04.png",
      "w": 86.7,
      "h": 128.67,
      "footX": 43.24,
      "footY": 128.88
     }
    ],
    "gameover": [
     {
      "src": "sprites/zombie/gameover/01.png",
      "w": 85.81,
      "h": 116.47,
      "footX": 42.82,
      "footY": 116.47
     },
     {
      "src": "sprites/zombie/gameover/02.png",
      "w": 87.39,
      "h": 131.97,
      "footX": 43.61,
      "footY": 131.97
     }
    ],
    "panic": [
     {
      "src": "sprites/zombie/panic/01.png",
      "w": 88.57,
      "h": 132.31,
      "footX": 46.88,
      "footY": 132.31
     },
     {
      "src": "sprites/zombie/panic/02.png",
      "w": 85.97,
      "h": 131.23,
      "footX": 42.88,
      "footY": 131.23
     },
     {
      "src": "sprites/zombie/panic/03.png",
      "w": 89.22,
      "h": 156.35,
      "footX": 46.67,
      "footY": 156.35
     },
     {
      "src": "sprites/zombie/panic/04.png",
      "w": 80.34,
      "h": 153.97,
      "footX": 40.6,
      "footY": 153.97
     }
    ],
    "pickup": [
     {
      "src": "sprites/zombie/pickup/01.png",
      "w": 96.05,
      "h": 112.48,
      "footX": 47.92,
      "footY": 112.48
     },
     {
      "src": "sprites/zombie/pickup/02.png",
      "w": 93.77,
      "h": 90.02,
      "footX": 46.78,
      "footY": 90.02
     },
     {
      "src": "sprites/zombie/pickup/03.png",
      "w": 93.35,
      "h": 116.43,
      "footX": 46.57,
      "footY": 116.43
     }
    ],
    "run_dribble_l": [
     {
      "src": "sprites/zombie/run_dribble_l/01.png",
      "w": 98.74,
      "h": 129.33,
      "footX": 34.49,
      "footY": 129.33
     },
     {
      "src": "sprites/zombie/run_dribble_l/02.png",
      "w": 66.31,
      "h": 132.41,
      "footX": 33.05,
      "footY": 132.41
     },
     {
      "src": "sprites/zombie/run_dribble_l/03.png",
      "w": 86.63,
      "h": 129.33,
      "footX": 43.01,
      "footY": 129.33
     },
     {
      "src": "sprites/zombie/run_dribble_l/04.png",
      "w": 72.67,
      "h": 129.33,
      "footX": 36.23,
      "footY": 129.33
     }
    ],
    "run_dribble_r": [
     {
      "src": "sprites/zombie/run_dribble_r/01.png",
      "w": 90.57,
      "h": 127.63,
      "footX": 57.67,
      "footY": 128.46
     },
     {
      "src": "sprites/zombie/run_dribble_r/02.png",
      "w": 61.84,
      "h": 129.09,
      "footX": 30.81,
      "footY": 129.09
     },
     {
      "src": "sprites/zombie/run_dribble_r/03.png",
      "w": 88.9,
      "h": 126.59,
      "footX": 45.8,
      "footY": 127.42
     },
     {
      "src": "sprites/zombie/run_dribble_r/04.png",
      "w": 56.42,
      "h": 128.46,
      "footX": 29.46,
      "footY": 128.46
     }
    ],
    "run_l": [
     {
      "src": "sprites/zombie/run_l/01.png",
      "w": 97.72,
      "h": 130.57,
      "footX": 41.21,
      "footY": 130.57
     },
     {
      "src": "sprites/zombie/run_l/02.png",
      "w": 61.21,
      "h": 128.53,
      "footX": 30.5,
      "footY": 131.18
     },
     {
      "src": "sprites/zombie/run_l/03.png",
      "w": 102.42,
      "h": 128.12,
      "footX": 39.89,
      "footY": 128.12
     },
     {
      "src": "sprites/zombie/run_l/04.png",
      "w": 58.96,
      "h": 128.12,
      "footX": 25.09,
      "footY": 128.12
     }
    ],
    "run_r": [
     {
      "src": "sprites/zombie/run_r/01.png",
      "w": 98.59,
      "h": 127.05,
      "footX": 54.66,
      "footY": 127.88
     },
     {
      "src": "sprites/zombie/run_r/02.png",
      "w": 69.51,
      "h": 128.29,
      "footX": 34.65,
      "footY": 128.29
     },
     {
      "src": "sprites/zombie/run_r/03.png",
      "w": 106.84,
      "h": 126.84,
      "footX": 65.48,
      "footY": 127.67
     },
     {
      "src": "sprites/zombie/run_r/04.png",
      "w": 58.16,
      "h": 127.46,
      "footX": 29.6,
      "footY": 127.46
     }
    ],
    "shot": [
     {
      "src": "sprites/zombie/shot/01.png",
      "w": 88.55,
      "h": 112.03,
      "footX": 44.15,
      "footY": 112.03
     },
     {
      "src": "sprites/zombie/shot/02.png",
      "w": 83.7,
      "h": 141.12,
      "footX": 41.72,
      "footY": 141.12
     },
     {
      "src": "sprites/zombie/shot/03.png",
      "w": 54.35,
      "h": 178.12,
      "footX": 27.05,
      "footY": 178.12
     },
     {
      "src": "sprites/zombie/shot/04.png",
      "w": 71.45,
      "h": 155.15,
      "footX": 35.6,
      "footY": 155.15
     }
    ],
    "steal_l": [
     {
      "src": "sprites/zombie/steal_l/01.png",
      "w": 101.23,
      "h": 119.01,
      "footX": 55.6,
      "footY": 119.01
     },
     {
      "src": "sprites/zombie/steal_l/02.png",
      "w": 160.2,
      "h": 110.55,
      "footX": 90.94,
      "footY": 112.07
     },
     {
      "src": "sprites/zombie/steal_l/03.png",
      "w": 89.96,
      "h": 122.26,
      "footX": 46.71,
      "footY": 123.56
     }
    ],
    "steal_r": [
     {
      "src": "sprites/zombie/steal_r/01.png",
      "w": 109.2,
      "h": 121.57,
      "footX": 50.84,
      "footY": 122.46
     },
     {
      "src": "sprites/zombie/steal_r/02.png",
      "w": 152.3,
      "h": 114.5,
      "footX": 66.31,
      "footY": 114.94
     },
     {
      "src": "sprites/zombie/steal_r/03.png",
      "w": 91.51,
      "h": 126.22,
      "footX": 45.65,
      "footY": 126.22
     }
    ],
    "stolen": [
     {
      "src": "sprites/zombie/stolen/01.png",
      "w": 88.47,
      "h": 121.93,
      "footX": 44.14,
      "footY": 122.12
     },
     {
      "src": "sprites/zombie/stolen/02.png",
      "w": 82.8,
      "h": 121.74,
      "footX": 41.31,
      "footY": 121.74
     },
     {
      "src": "sprites/zombie/stolen/03.png",
      "w": 75.05,
      "h": 149.34,
      "footX": 37.43,
      "footY": 149.34
     }
    ],
    "turn": [
     {
      "src": "sprites/zombie/turn/01.png",
      "w": 88.53,
      "h": 135.76,
      "footX": 44.17,
      "footY": 135.96
     },
     {
      "src": "sprites/zombie/turn/02.png",
      "w": 95.84,
      "h": 135.56,
      "footX": 47.82,
      "footY": 135.56
     }
    ]
   },
   "ballSide": {
    "dribble_idle": -1,
    "run_dribble_l": -1,
    "break_face": -1,
    "break_head": -1,
    "panic": -1
   },
   "apexFrame": {
    "dribble_idle": 2,
    "run_dribble_r": 1,
    "run_dribble_l": 1
   },
   "loopBounces": {
    "run_dribble_r": 2,
    "run_dribble_l": 2
   },
   "storySeq": {
    "break_face": null,
    "break_head": null,
    "panic": [
     2,
     3
    ]
   },
   "standH": 132.0,
   "pickupBall": [
    [
     0,
     0
    ],
    [
     0,
     0
    ],
    [
     0,
     0.42
    ]
   ],
   "handX": 8.1,
   "handY": -178.12
  }
 ]
};
