// Generated by tools/build-sprites.py -- do not edit by hand.
window.SPRITE_MANIFEST = {
 "standingHeight": 132,
 "characters": [
  {
   "key": "monkey",
   "label": "Monkey",
   "mirror": false,
   "sequences": {
    "aim": [
     {
      "src": "sprites/monkey/aim/01.png",
      "w": 90.36,
      "h": 132.03,
      "footX": 49.47,
      "footY": 132.03
     },
     {
      "src": "sprites/monkey/aim/02.png",
      "w": 93.64,
      "h": 127.5,
      "footX": 52.12,
      "footY": 127.5
     }
    ],
    "break_banana": [
     {
      "src": "sprites/monkey/break_banana/01.png",
      "w": 116.61,
      "h": 138.5,
      "footX": 60.58,
      "footY": 138.5
     },
     {
      "src": "sprites/monkey/break_banana/02.png",
      "w": 110.11,
      "h": 138.5,
      "footX": 54.95,
      "footY": 138.5
     },
     {
      "src": "sprites/monkey/break_banana/03.png",
      "w": 108.59,
      "h": 138.29,
      "footX": 54.19,
      "footY": 138.29
     },
     {
      "src": "sprites/monkey/break_banana/04.png",
      "w": 123.55,
      "h": 137.42,
      "footX": 57.55,
      "footY": 137.42
     }
    ],
    "break_wave": [
     {
      "src": "sprites/monkey/break_wave/01.png",
      "w": 106.46,
      "h": 144.34,
      "footX": 54.46,
      "footY": 144.34
     },
     {
      "src": "sprites/monkey/break_wave/02.png",
      "w": 109.34,
      "h": 126.02,
      "footX": 51.68,
      "footY": 126.02
     },
     {
      "src": "sprites/monkey/break_wave/03.png",
      "w": 112.84,
      "h": 128.08,
      "footX": 52.2,
      "footY": 128.08
     },
     {
      "src": "sprites/monkey/break_wave/04.png",
      "w": 104.81,
      "h": 123.55,
      "footX": 52.4,
      "footY": 123.55
     }
    ],
    "celebrate": [
     {
      "src": "sprites/monkey/celebrate/01.png",
      "w": 106.81,
      "h": 174.91,
      "footX": 47.02,
      "footY": 174.91
     },
     {
      "src": "sprites/monkey/celebrate/02.png",
      "w": 109.67,
      "h": 138.29,
      "footX": 53.5,
      "footY": 138.29
     }
    ],
    "charge": [
     {
      "src": "sprites/monkey/charge/01.png",
      "w": 102.89,
      "h": 131.41,
      "footX": 59.18,
      "footY": 131.41
     },
     {
      "src": "sprites/monkey/charge/02.png",
      "w": 95.07,
      "h": 116.13,
      "footX": 50.89,
      "footY": 116.13
     },
     {
      "src": "sprites/monkey/charge/03.png",
      "w": 95.44,
      "h": 98.61,
      "footX": 50.8,
      "footY": 98.61
     }
    ],
    "dribble_idle": [
     {
      "src": "sprites/monkey/dribble_idle/01.png",
      "w": 111.41,
      "h": 132.0,
      "footX": 56.03,
      "footY": 132.0
     },
     {
      "src": "sprites/monkey/dribble_idle/02.png",
      "w": 108.59,
      "h": 133.08,
      "footX": 53.43,
      "footY": 133.08
     },
     {
      "src": "sprites/monkey/dribble_idle/03.png",
      "w": 108.59,
      "h": 134.6,
      "footX": 53.75,
      "footY": 134.6
     },
     {
      "src": "sprites/monkey/dribble_idle/04.png",
      "w": 109.89,
      "h": 132.43,
      "footX": 55.92,
      "footY": 132.43
     }
    ],
    "gameover": [
     {
      "src": "sprites/monkey/gameover/01.png",
      "w": 109.59,
      "h": 123.11,
      "footX": 54.71,
      "footY": 123.11
     },
     {
      "src": "sprites/monkey/gameover/02.png",
      "w": 109.41,
      "h": 130.4,
      "footX": 54.62,
      "footY": 130.4
     }
    ],
    "pickup": [
     {
      "src": "sprites/monkey/pickup/01.png",
      "w": 110.54,
      "h": 115.7,
      "footX": 55.18,
      "footY": 116.25
     },
     {
      "src": "sprites/monkey/pickup/02.png",
      "w": 110.73,
      "h": 128.04,
      "footX": 55.27,
      "footY": 128.04
     },
     {
      "src": "sprites/monkey/pickup/03.png",
      "w": 111.46,
      "h": 130.99,
      "footX": 57.85,
      "footY": 131.54
     }
    ],
    "run_dribble_l": [
     {
      "src": "sprites/monkey/run_dribble_l/01.png",
      "w": 118.56,
      "h": 133.73,
      "footX": 57.55,
      "footY": 133.73
     },
     {
      "src": "sprites/monkey/run_dribble_l/02.png",
      "w": 109.67,
      "h": 132.43,
      "footX": 59.28,
      "footY": 133.73
     },
     {
      "src": "sprites/monkey/run_dribble_l/03.png",
      "w": 116.39,
      "h": 133.73,
      "footX": 57.55,
      "footY": 133.73
     },
     {
      "src": "sprites/monkey/run_dribble_l/04.png",
      "w": 102.52,
      "h": 132.22,
      "footX": 55.16,
      "footY": 133.52
     }
    ],
    "run_dribble_r": [
     {
      "src": "sprites/monkey/run_dribble_r/01.png",
      "w": 111.84,
      "h": 137.2,
      "footX": 51.48,
      "footY": 138.07
     },
     {
      "src": "sprites/monkey/run_dribble_r/02.png",
      "w": 107.72,
      "h": 136.77,
      "footX": 58.85,
      "footY": 138.07
     },
     {
      "src": "sprites/monkey/run_dribble_r/03.png",
      "w": 118.56,
      "h": 138.07,
      "footX": 57.76,
      "footY": 138.07
     },
     {
      "src": "sprites/monkey/run_dribble_r/04.png",
      "w": 111.41,
      "h": 138.07,
      "footX": 60.15,
      "footY": 138.07
     }
    ],
    "run_l": [
     {
      "src": "sprites/monkey/run_l/01.png",
      "w": 134.49,
      "h": 127.21,
      "footX": 64.4,
      "footY": 127.21
     },
     {
      "src": "sprites/monkey/run_l/02.png",
      "w": 130.85,
      "h": 127.21,
      "footX": 64.71,
      "footY": 127.21
     }
    ],
    "run_r": [
     {
      "src": "sprites/monkey/run_r/01.png",
      "w": 132.38,
      "h": 126.63,
      "footX": 61.29,
      "footY": 126.63
     },
     {
      "src": "sprites/monkey/run_r/02.png",
      "w": 124.6,
      "h": 126.63,
      "footX": 62.47,
      "footY": 126.63
     }
    ],
    "shot": [
     {
      "src": "sprites/monkey/shot/01.png",
      "w": 88.02,
      "h": 99.63,
      "footX": 45.33,
      "footY": 99.63
     },
     {
      "src": "sprites/monkey/shot/02.png",
      "w": 99.02,
      "h": 137.53,
      "footX": 60.51,
      "footY": 137.73
     },
     {
      "src": "sprites/monkey/shot/03.png",
      "w": 89.04,
      "h": 164.22,
      "footX": 55.52,
      "footY": 165.64
     },
     {
      "src": "sprites/monkey/shot/04.png",
      "w": 77.42,
      "h": 155.86,
      "footX": 44.62,
      "footY": 156.07
     }
    ],
    "turn": [
     {
      "src": "sprites/monkey/turn/01.png",
      "w": 108.43,
      "h": 132.0,
      "footX": 59.59,
      "footY": 132.0
     },
     {
      "src": "sprites/monkey/turn/02.png",
      "w": 100.51,
      "h": 131.06,
      "footX": 52.42,
      "footY": 131.06
     }
    ]
   },
   "ballSide": {
    "dribble_idle": -1,
    "break_banana": -1,
    "break_wave": -1,
    "pickup": -1,
    "run_dribble_r": 1,
    "run_dribble_l": -1
   },
   "handX": 15.51,
   "handY": -165.64
  },
  {
   "key": "nba",
   "label": "NBA Player",
   "mirror": true,
   "sequences": {
    "dribble_idle": [
     {
      "src": "sprites/nba/dribble_idle/01.png",
      "w": 88.25,
      "h": 132.0,
      "footX": 45.85,
      "footY": 132.0
     },
     {
      "src": "sprites/nba/dribble_idle/02.png",
      "w": 84.24,
      "h": 128.36,
      "footX": 42.45,
      "footY": 128.36
     }
    ],
    "run_dribble_r": [
     {
      "src": "sprites/nba/run_dribble_r/01.png",
      "w": 88.25,
      "h": 132.0,
      "footX": 45.85,
      "footY": 132.0
     },
     {
      "src": "sprites/nba/run_dribble_r/02.png",
      "w": 84.24,
      "h": 128.36,
      "footX": 42.45,
      "footY": 128.36
     }
    ],
    "run_dribble_l": [
     {
      "src": "sprites/nba/run_dribble_l/01.png",
      "w": 88.25,
      "h": 132.0,
      "footX": 45.85,
      "footY": 132.0
     },
     {
      "src": "sprites/nba/run_dribble_l/02.png",
      "w": 84.24,
      "h": 128.36,
      "footX": 42.45,
      "footY": 128.36
     }
    ],
    "run_r": [
     {
      "src": "sprites/nba/run_r/01.png",
      "w": 88.25,
      "h": 132.0,
      "footX": 45.85,
      "footY": 132.0
     },
     {
      "src": "sprites/nba/run_r/02.png",
      "w": 84.24,
      "h": 128.36,
      "footX": 42.45,
      "footY": 128.36
     }
    ],
    "run_l": [
     {
      "src": "sprites/nba/run_l/01.png",
      "w": 88.25,
      "h": 132.0,
      "footX": 45.85,
      "footY": 132.0
     },
     {
      "src": "sprites/nba/run_l/02.png",
      "w": 84.24,
      "h": 128.36,
      "footX": 42.45,
      "footY": 128.36
     }
    ],
    "aim": [
     {
      "src": "sprites/nba/aim/01.png",
      "w": 93.01,
      "h": 127.34,
      "footX": 46.13,
      "footY": 127.34
     },
     {
      "src": "sprites/nba/aim/02.png",
      "w": 86.94,
      "h": 127.06,
      "footX": 15.25,
      "footY": 127.06
     }
    ],
    "charge": [
     {
      "src": "sprites/nba/charge/01.png",
      "w": 75.56,
      "h": 132.47,
      "footX": 37.73,
      "footY": 132.47
     },
     {
      "src": "sprites/nba/charge/02.png",
      "w": 86.94,
      "h": 127.06,
      "footX": 15.25,
      "footY": 127.06
     }
    ],
    "shot": [
     {
      "src": "sprites/nba/shot/01.png",
      "w": 53.45,
      "h": 129.01,
      "footX": 19.08,
      "footY": 129.01
     },
     {
      "src": "sprites/nba/shot/02.png",
      "w": 82.74,
      "h": 130.51,
      "footX": 41.47,
      "footY": 130.51
     }
    ]
   },
   "ballSide": {},
   "handX": 13.39,
   "handY": -129.01
  },
  {
   "key": "highschooler",
   "label": "High Schooler",
   "mirror": true,
   "sequences": {
    "dribble_idle": [
     {
      "src": "sprites/highschooler/dribble_idle/01.png",
      "w": 81.97,
      "h": 132.0,
      "footX": 75.0,
      "footY": 132.0
     },
     {
      "src": "sprites/highschooler/dribble_idle/02.png",
      "w": 82.35,
      "h": 131.91,
      "footX": 43.49,
      "footY": 131.91
     }
    ],
    "run_dribble_r": [
     {
      "src": "sprites/highschooler/run_dribble_r/01.png",
      "w": 81.97,
      "h": 132.0,
      "footX": 75.0,
      "footY": 132.0
     },
     {
      "src": "sprites/highschooler/run_dribble_r/02.png",
      "w": 82.35,
      "h": 131.91,
      "footX": 43.49,
      "footY": 131.91
     }
    ],
    "run_dribble_l": [
     {
      "src": "sprites/highschooler/run_dribble_l/01.png",
      "w": 81.97,
      "h": 132.0,
      "footX": 75.0,
      "footY": 132.0
     },
     {
      "src": "sprites/highschooler/run_dribble_l/02.png",
      "w": 82.35,
      "h": 131.91,
      "footX": 43.49,
      "footY": 131.91
     }
    ],
    "run_r": [
     {
      "src": "sprites/highschooler/run_r/01.png",
      "w": 81.97,
      "h": 132.0,
      "footX": 75.0,
      "footY": 132.0
     },
     {
      "src": "sprites/highschooler/run_r/02.png",
      "w": 82.35,
      "h": 131.91,
      "footX": 43.49,
      "footY": 131.91
     }
    ],
    "run_l": [
     {
      "src": "sprites/highschooler/run_l/01.png",
      "w": 81.97,
      "h": 132.0,
      "footX": 75.0,
      "footY": 132.0
     },
     {
      "src": "sprites/highschooler/run_l/02.png",
      "w": 82.35,
      "h": 131.91,
      "footX": 43.49,
      "footY": 131.91
     }
    ],
    "aim": [
     {
      "src": "sprites/highschooler/aim/01.png",
      "w": 85.95,
      "h": 129.63,
      "footX": 43.35,
      "footY": 129.63
     },
     {
      "src": "sprites/highschooler/aim/02.png",
      "w": 83.29,
      "h": 126.6,
      "footX": 76.09,
      "footY": 126.6
     }
    ],
    "charge": [
     {
      "src": "sprites/highschooler/charge/01.png",
      "w": 81.4,
      "h": 125.37,
      "footX": 40.65,
      "footY": 125.37
     },
     {
      "src": "sprites/highschooler/charge/02.png",
      "w": 56.95,
      "h": 129.44,
      "footX": 28.81,
      "footY": 129.44
     }
    ],
    "shot": [
     {
      "src": "sprites/highschooler/shot/01.png",
      "w": 45.11,
      "h": 131.34,
      "footX": 15.64,
      "footY": 131.34
     },
     {
      "src": "sprites/highschooler/shot/02.png",
      "w": 75.24,
      "h": 131.72,
      "footX": 36.39,
      "footY": 131.72
     }
    ]
   },
   "ballSide": {},
   "handX": 14.68,
   "handY": -131.34
  },
  {
   "key": "zombie",
   "label": "Zombie",
   "mirror": true,
   "sequences": {
    "dribble_idle": [
     {
      "src": "sprites/zombie/dribble_idle/01.png",
      "w": 91.96,
      "h": 132.0,
      "footX": 46.31,
      "footY": 132.0
     },
     {
      "src": "sprites/zombie/dribble_idle/02.png",
      "w": 92.63,
      "h": 126.73,
      "footX": 49.14,
      "footY": 126.73
     }
    ],
    "run_dribble_r": [
     {
      "src": "sprites/zombie/run_dribble_r/01.png",
      "w": 91.96,
      "h": 132.0,
      "footX": 46.31,
      "footY": 132.0
     },
     {
      "src": "sprites/zombie/run_dribble_r/02.png",
      "w": 92.63,
      "h": 126.73,
      "footX": 49.14,
      "footY": 126.73
     }
    ],
    "run_dribble_l": [
     {
      "src": "sprites/zombie/run_dribble_l/01.png",
      "w": 91.96,
      "h": 132.0,
      "footX": 46.31,
      "footY": 132.0
     },
     {
      "src": "sprites/zombie/run_dribble_l/02.png",
      "w": 92.63,
      "h": 126.73,
      "footX": 49.14,
      "footY": 126.73
     }
    ],
    "run_r": [
     {
      "src": "sprites/zombie/run_r/01.png",
      "w": 91.96,
      "h": 132.0,
      "footX": 46.31,
      "footY": 132.0
     },
     {
      "src": "sprites/zombie/run_r/02.png",
      "w": 92.63,
      "h": 126.73,
      "footX": 49.14,
      "footY": 126.73
     }
    ],
    "run_l": [
     {
      "src": "sprites/zombie/run_l/01.png",
      "w": 91.96,
      "h": 132.0,
      "footX": 46.31,
      "footY": 132.0
     },
     {
      "src": "sprites/zombie/run_l/02.png",
      "w": 92.63,
      "h": 126.73,
      "footX": 49.14,
      "footY": 126.73
     }
    ],
    "aim": [
     {
      "src": "sprites/zombie/aim/01.png",
      "w": 90.62,
      "h": 128.36,
      "footX": 43.97,
      "footY": 128.36
     },
     {
      "src": "sprites/zombie/aim/02.png",
      "w": 86.31,
      "h": 118.97,
      "footX": 49.86,
      "footY": 118.97
     }
    ],
    "charge": [
     {
      "src": "sprites/zombie/charge/01.png",
      "w": 61.79,
      "h": 133.53,
      "footX": 30.89,
      "footY": 133.53
     },
     {
      "src": "sprites/zombie/charge/02.png",
      "w": 58.62,
      "h": 134.2,
      "footX": 29.31,
      "footY": 134.2
     }
    ],
    "shot": [
     {
      "src": "sprites/zombie/shot/01.png",
      "w": 77.49,
      "h": 131.71,
      "footX": 46.84,
      "footY": 131.71
     },
     {
      "src": "sprites/zombie/shot/02.png",
      "w": 76.92,
      "h": 127.98,
      "footX": 43.78,
      "footY": 127.98
     }
    ]
   },
   "ballSide": {},
   "handX": 22.65,
   "handY": -131.71
  }
 ]
};
