#!/usr/bin/env python3
"""Prepare the generated audio for the game to load.

    python tools/build-audio-web.py

Two jobs, both about how long the player waits rather than how anything sounds.

FLAC for the music
------------------
The tracks are 11,025 Hz mono 16-bit PCM: two and a half megabytes for two
minutes, and on a disk where every read is scanned first that is most of the
wait before the first note. FLAC is lossless -- the decoded samples are
bit-identical, which matters here because the 8-bit crunch these tracks are
built around is exactly the broadband noise a lossy codec spends its bits
fighting. Measured against this material, Opus at 64 kbps came out *larger* than
FLAC and moved the waveform by 7% RMS.

The WAVs stay where they are; the game prefers the FLAC and falls back to them.

The effects, inlined
--------------------
Twelve one-shots, 73 KB in total. As files they are twelve disk reads that have
to finish before a bounce can be heard, and off a file:// page they cannot be
fetched at all, which is what pushed effects onto <audio> elements. Base64'd
into one script they are zero reads, available before the first tap, and decoded
straight into Web Audio on every protocol -- which is the only way an effect is
in time with the frame that fired it.
"""

from __future__ import annotations

import base64
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AUDIO = ROOT / "audio"

MUSIC = [
    AUDIO / "full-court-pressure" / "full-court-pressure.wav",
    AUDIO / "overtime-overdrive" / "overtime-overdrive.wav",
    AUDIO / "victory-lap" / "victory-lap-loop.wav",
    AUDIO / "victory-lap" / "victory-sting.wav",
]
SFX_DIR = AUDIO / "basketball-natural" / "wav"
SFX_OUT = AUDIO / "sfx-data.js"


def flac_music() -> None:
    if not shutil.which("ffmpeg"):
        print("ffmpeg not found - skipping the music; the game will use the WAVs")
        return
    before = after = 0
    for src in MUSIC:
        if not src.exists():
            print(f"{src.name:<28} SKIPPED (missing)")
            continue
        dest = src.with_suffix(".flac")
        r = subprocess.run(
            ["ffmpeg", "-y", "-loglevel", "error", "-i", str(src),
             "-c:a", "flac", "-compression_level", "12", str(dest)],
            capture_output=True, text=True)
        if r.returncode != 0:
            print(f"{src.name:<28} FAILED: {r.stderr.strip()[:80]}")
            continue
        b, a = src.stat().st_size, dest.stat().st_size
        before += b
        after += a
        print(f"{src.name:<28} {b/1024:7.0f} KB -> {dest.name:<28} {a/1024:6.0f} KB   ({a*100/b:.0f}%)")
    if before:
        print(f"music: {before/1e6:.1f} MB -> {after/1e6:.1f} MB\n")


def inline_sfx() -> None:
    clips = {}
    for src in sorted(SFX_DIR.glob("*.wav")):
        clips[src.stem] = base64.b64encode(src.read_bytes()).decode("ascii")
    if not clips:
        print(f"no effects found in {SFX_DIR}")
        return
    raw = sum(len(base64.b64decode(v)) for v in clips.values())
    body = ",\n".join(f'  "{k}": "{v}"' for k, v in sorted(clips.items()))
    SFX_OUT.write_text(
        "// Generated by tools/build-audio-web.py -- do not edit.\n"
        "// The twelve effect one-shots, base64'd, so they cost no disk reads and\n"
        "// can be decoded into Web Audio even from a file:// page, where fetch()\n"
        "// refuses to read anything at all.\n"
        "window.SFX_DATA = {\n" + body + "\n};\n",
        encoding="utf-8", newline="\n")
    print(f"effects: {len(clips)} clips, {raw/1024:.0f} KB raw -> "
          f"{SFX_OUT.relative_to(ROOT)} {SFX_OUT.stat().st_size/1024:.0f} KB, zero reads")


def main() -> None:
    flac_music()
    inline_sfx()


if __name__ == "__main__":
    main()
