#!/usr/bin/env python3
"""Export what the browser needs to re-render the music from its score.

    python tools/export-score-data.py        # -> audio/score-data.js, score-rest.js

The tracks are synthesised, not recorded, so the score plus the synth *is* the
music. Shipping the score instead of the audio takes the menu track from 667 KB
of FLAC to 202 KB, which matters on a disk where every read is scanned first.

Two things have to come across as data rather than as code:

- **The percussion.** `percussion()` builds its noise with
  `np.random.default_rng(seed)`, and numpy's PCG64 stream cannot be reproduced
  in JavaScript without reimplementing PCG64 and numpy's SeedSequence exactly.
  Thirteen buffers, 26k samples in total, are dumped as float32 instead.
  Pitched instruments are pure sin/exp arithmetic and port directly.
- **The event list**, compacted: parts as indices, numbers rounded to what
  11 kHz at these tempos can actually resolve.

Run this after any build-*.py that changes a score. audio/synth.js is the
consumer; tools/test-synth.js is the check that it still matches the WAVs.
"""
from __future__ import annotations

import base64
import importlib.util
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"


def load(name):
    spec = importlib.util.spec_from_file_location(name.replace("-", "_"), TOOLS / name)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def b64_float32(a: np.ndarray) -> str:
    """float32. int16 was tried first and left 829 samples differing by one
    quantisation step: its 1.5e-5 error survived into the master peak, which is
    a max and so cannot average away. float32 is ~1e-7 and costs 70 KB more."""
    return base64.b64encode(a.astype("<f4").tobytes()).decode("ascii")


def compact(events, parts_out):
    """[partIndex, beat, gain, midi|null, lengthBeats|null, echo|variant]"""
    rows = []
    for e in events:
        part = e["part"]
        if part not in parts_out:
            parts_out.append(part)
        i = parts_out.index(part)
        if "note" in e:
            rows.append([i, round(e["beat"], 4), round(e["gain"], 5),
                         e["note"], e["lengthBeats"], 1 if e.get("echo") else 0])
        else:
            rows.append([i, round(e["beat"], 4), round(e["gain"], 5),
                         None, None, e.get("variant", 0)])
    return rows


def main() -> None:
    engine = load("build-full-court-soundtrack.py")

    perc = {}
    wanted = [("kick", 0), ("snare", 0), ("snare", 1), ("snare", 2), ("clap", 0),
              ("hat", 0), ("hat", 1), ("hat", 2), ("open", 0), ("tom", 0),
              ("tom", 1), ("tom", 2), ("crash", 0)]
    total = 0
    for kind, variant in wanted:
        y = engine.percussion(kind, variant)
        perc["%s:%d" % (kind, variant)] = {"d": b64_float32(y), "n": len(y)}
        total += len(y)

    out = {"sampleRate": engine.SR, "perc": perc, "tracks": {}}

    # The kick ducking differs per track, so it travels with the score rather
    # than being hard-coded in the synth.
    tracks = [
        ("menu", "full-court-pressure", 128, "voices_fullcourt",
         {"secs": 0.13, "amount": 0.18, "decay": 0.043, "floors": {"bass": 0.66}}),
        ("play", "overtime-overdrive", 144, "voices_overtime",
         {"secs": 0.14, "amount": 0.23, "decay": 0.048, "floors": {"bass": 0.6, "keys": 0.75}}),
    ]
    for key, folder, bpm, voices, duck in tracks:
        f = ROOT / "audio" / folder / "score.json"
        if not f.exists():
            print("%-8s SKIPPED (no score.json)" % key)
            continue
        ev = json.loads(f.read_text())
        parts: list[str] = []
        rows = compact(ev, parts)
        out["tracks"][key] = {"bpm": bpm, "seconds": 120, "voices": voices,
                              "duck": duck, "parts": parts, "events": rows}
        print("%-8s %5d events, %2d parts" % (key, len(rows), len(parts)))

    # The victory music is deliberately not here. It uses a different engine --
    # its own arrangement class, echo measured in seconds rather than beats, no
    # buses and no ducking -- and it is the least urgent track in the game, so it
    # stays on FLAC until there is a reason to port a second engine.

    head = ("// Generated by tools/export-score-data.py -- do not edit.\n"
            "// The scores, plus the percussion buffers that cannot be reproduced in\n"
            "// JavaScript (numpy's PCG64 noise). Everything else is synthesised there.\n")
    # Two files, because the menu track is the one the player is waiting on and
    # it should not have to read the anthem's score to start.
    core = {"sampleRate": out["sampleRate"], "perc": out["perc"],
            "tracks": {"menu": out["tracks"]["menu"]}}
    rest = {"tracks": {k: v for k, v in out["tracks"].items() if k != "menu"}}

    a = ROOT / "audio" / "score-data.js"
    a.write_text(head + "window.SCORE_DATA = " + json.dumps(core, separators=(",", ":")) + ";\n",
                 encoding="utf-8", newline="\n")
    b = ROOT / "audio" / "score-rest.js"
    b.write_text(head + "window.SCORE_REST = " + json.dumps(rest, separators=(",", ":")) + ";\n",
                 encoding="utf-8", newline="\n")
    print("\npercussion: %d buffers, %d samples" % (len(perc), total))
    print("score-data.js (percussion + menu track): %.0f KB" % (a.stat().st_size / 1024))
    print("score-rest.js (everything after it)    : %.0f KB" % (b.stat().st_size / 1024))


if __name__ == "__main__":
    main()
