// Generated by tools/build-splash.py -- do not edit.
// The mode screen is one base painting plus a small patch per variation;
// x/y/w/h are fractions of the base, so they survive a re-render at any size.
window.SPLASH_MANIFEST = {
  "base": "mode-0",
  "select": "select",
  "source": {
    "w": 1448,
    "h": 1086
  },
  "variations": [
    {
      "name": "mode-1",
      "x": 0.353591,
      "y": 0.353591,
      "w": 0.154696,
      "h": 0.206262
    },
    {
      "name": "mode-2",
      "x": 0.143646,
      "y": 0.515654,
      "w": 0.088398,
      "h": 0.132597
    },
    {
      "name": "mode-3",
      "x": 0.585635,
      "y": 0.25046,
      "w": 0.132597,
      "h": 0.176796
    },
    {
      "name": "mode-4",
      "x": 0.80663,
      "y": 0.574586,
      "w": 0.110497,
      "h": 0.191529
    }
  ]
};
